source 'https://github.com/CocoaPods/Specs.git'

target 'UICategory', :exclusive => true do
  pod "UICategory", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UICategory", :path => "../"

  
end
